export const CREATE_EXPENSE_REQUEST = 'CREATE_EXPENSE_REQUEST'
export const CREATE_EXPENSE_FAIL = 'CREATE_EXPENSE_FAIL'
export const CREATE_EXPENSE_SUCCESS = 'CREATE_EXPENSE_SUCCESS'

export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL'

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL'
export const LOGOUT_USER =  'LOGOUT_USER'

export const AVERAGE_CATEGORY_REQUEST = 'AVERAGE_CATEGORY_REQUEST'
export const AVERAGE_CATEGORY_SUCCESS = 'AVERAGE_CATEGORY_SUCCESS'
export const AVERAGE_CATEGORY_FAIL = 'AVERAGE_CATEGORY_FAIL'
