export const CREATE_EXPENSE_REQUEST = 'CREATE_EXPENSE_REQUEST'
export const CREATE_EXPENSE_FAIL = 'CREATE_EXPENSE_FAIL'
export const CREATE_EXPENSE_SUCCESS = 'CREATE_EXPENSE_SUCCESS'

export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
